name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Get app version
      id: get_version
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Configure Git committer
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Git tag
      run: |
        git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
        git push origin v${{ env.VERSION }}

    - name: Build
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        BINARY_NAME=$REPO_NAME
        go build -v -ldflags "-X main.version=${{ env.VERSION }}" -o $BINARY_NAME .
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: CHANGELOG.txt
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./${{ env.BINARY_NAME }} 
