name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Get app version
      id: get_version
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Configure Git committer
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Git tag
      run: |
        git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
        git push origin v${{ env.VERSION }} --push-option=authToken=${{ secrets.GITHUB_TOKEN }}

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'cmtbot'
          compress: 'true'
          dest: 'dist'

    - name: Upload build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "./dist/*.tar.gz"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: CHANGELOG.txt
        tag_name: v${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./dist 
